### ISSUE TITLE
Uploading Termbases on Baseterm

### ISSUE THREAD

**Issue by chuckvale** [BYU-TRG-Team/baseterm#16]
I was testing Baseterm and its ability to export and import termbases and this is what I've found while doing tests with the service missionary file.  I used the "add concept entry" feature of Baseterm to add 3 new entries for the term "senior companion" in Korean, Portuguese, and Spanish.  After adding these entries, I exported the service missionary termbase.  Right after exporting it, I immediately tried to re-upload it, but I received an error message from Baseterm, seen below: 

![image (1)](https://user-images.githubusercontent.com/35540577/216145423-df9e4abf-bf71-4476-9ab2-efa4a01abdc4.png)

When I looked in the code, there is a "target" element in the transacNote tag that is throwing this error, and it is added twice to every concept entry added through BaseTerm.  Here is the specific target element and a screenshot of the Korean entry:

target="BT-c50d39e8-f7e0-439a-a0a9-fbe8102dba3f"

<img width="548" alt="image (2)" src="https://user-images.githubusercontent.com/35540577/216145510-f11ca1fd-9be2-4087-ad08-07932c49376d.png">

Once all instances of this were removed from the file, I reuploaded it to BaseTerm successfully.  I'm not sure why this "target" element is being created, but it only appears on concept entries made in BaseTerm.  I'll attach both versions of the file so you guys can compare them.  

Chad

**Comment by Andrew-Dame** [comment]
@chuckvale 

This issue has to do with `transacGrp` and `refObject` elements that are automatically created when a term, language section, or concept entry are created in BaseTerm. 

BaseTerm creates a `refObject` element for your specific user account when you first start editing a termbase. The id for this `refObject` element is formed by taking `BT-` and appending it to your account's user id (hence the target value you see). `transacGrp` elements that are automatically created when you create a term, language section, or concept entry are then linked to this `refObject` element.

There is a bug in this process where if the originally uploaded termbase does not contain a `back` element, none of the `refObject` elements are exported, and thus there is no element referenced by the target value in the `transacGrp` elements. 

A fix is being worked on this and should be released within the week.
